sim_params:
  is2d: 'true'
  N: 268435456
  nx: 16384
  ny: 16384
  dx: 8.5e-08
  z_detector: 4.0
  detector_size: 0.00085
  detector_size_y: 0.00085
  detector_pixel_size_x: 2e-07
  detector_pixel_size_y: 2e-07
  chunk_size: 134217728
use_disk_vector: false
save_final_u_vectors: false
save_debug_wavefields: false
dtype: c8
multisource:
  type: points
  energy_range:
    - 9999
    - 10001
  x_range:
    - -1e-06
    - 1e-06
  y_range:
    - -1e-06
    - 1e-06
  z: 0.0
  nr_source_points: 1
  seed: 1
elements:
  - type: sample
    z_start: 1.0
    pixel_size_x: 5e-08
    pixel_size_y: 5e-08
    pixel_size_z: 5e-08
    grid_path: thin_c10_vacuum.npy
    materials:
      -   - C
          - 1.5
    x_positions:
      - 0
    y_positions:
      - 0
